echo alerts

diff --git a/.github/actions/gitleaks-scan/action.yml b/.github/actions/gitleaks-scan/action.yml
--- a/.github/actions/gitleaks-scan/action.yml
+++ b/.github/actions/gitleaks-scan/action.yml
@@ -16,7 +16,21 @@ runs:
         ghcr.io/gitleaks/gitleaks:latest \
         git --log-opts "-1" \
         -f json \
-        -r gitleaks-${{ github.event.repository.name }}-${{ github.ref_name }}.json 
+        -r gitleaks-${{ github.event.repository.name }}-${{ github.ref_name }}.json \
+        || SECRET_EXIT_CODE=$?
+
+        if [ -z $SECRET_EXIT_CODE ]
+          then
+            echo "Secrets has not been found"
+          exit 0
+        elif [ $SECRET_EXIT_CODE = "1" ]
+        then
+          echo "Secrets or error encountered"
+          exit 1
+        else
+          echo "Error has been occured"
+        fi
+
 
     - name: Upload gitleaks report to artifacts
       uses: actions/upload-artifact@v4
