test

diff --git a/.github/actions/hadolint-scan/action.yml b/.github/actions/hadolint-scan/action.yml
--- a/.github/actions/hadolint-scan/action.yml
+++ b/.github/actions/hadolint-scan/action.yml
@@ -22,15 +22,17 @@ runs:
         fi
 
         for file in "${files[@]}"; do
-          cat $file
-
           echo "Scanning: $file"
           flat_name=$(echo "$file" | tr '/' '-' | sed 's/^-//')
           report_name="${flat_name}-hadolint.json"
-          docker run --rm -i --entrypoint /bin/hadolint \
-            hadolint/hadolint -f json - < $file | \
-            jq '.[].file |= "$file"' > "$report_name"
-          echo "Saved report to $report_name"
+
+          if ! cat "$file" | docker run --rm -i --entrypoint /bin/hadolint \
+            hadolint/hadolint -f json - | jq --arg f "$file" '.[].file |= $f' > "$report_name"; then
+            echo "⚠️ Hadolint scan failed for: $file"
+            continue
+          fi
+
+          echo "✅ Saved report to $report_name"
         done
 
     - name: Upload all Hadolint reports
