test

diff --git a/.github/actions/hadolint-scan/action.yml b/.github/actions/hadolint-scan/action.yml
--- a/.github/actions/hadolint-scan/action.yml
+++ b/.github/actions/hadolint-scan/action.yml
@@ -20,17 +20,24 @@ runs:
           echo "No Dockerfiles found. Exiting."
           exit 0
         fi
-        
-        echo ${files[@]}
 
         for file in "${files[@]}"; do
           echo "Scanning: $file"
           flat_name=$(echo "$file" | tr '/' '-' | sed 's/^-//')
           report_name="${flat_name}-hadolint.json"
-          docker run --rm -i --entrypoint /bin/hadolint \
-            hadolint/hadolint -f json - < "$file" | \
-            jq '.[].file |= "'"$file"'"' > "$report_name"
-          echo "Saved report to $report_name"
+
+          # Выполняем scan и обрабатываем ошибки
+          if ! docker run --rm -i --entrypoint /bin/hadolint \
+            hadolint/hadolint -f json - < "$file" 2> err.log | \
+            jq --arg f "$file" '.[].file |= $f' > "$report_name"; then
+
+            echo "⚠️ Hadolint scan failed for: $file"
+            cat err.log
+            rm -f "$report_name"
+            continue
+          fi
+
+          echo "✅ Saved report to $report_name"
         done
 
     - name: Upload all Hadolint reports
